name: Deploy CloudFormation Stack

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Package Lambda code
      run: |
        cd lambda
        zip function.zip index.js
        aws s3 cp function.zip s3://your-lambda-code-bucket/

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --stack-name my-stack \
          --template-file infra.yml \
          --parameter-overrides LambdaS3Bucket=your-lambda-code-bucket LambdaS3Key=function.zip \
          --capabilities CAPABILITY_IAM
